// apps/blog/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import axios from 'axios'
import { type Blog } from 'types'

const blogs = ref<Blog[]>([])

axios.get('http://localhost:8000/blogs').then((res) => {
  blogs.value = res.data.blogs
})
</script>

<template>
  <main>
    <div v-for="blog in blogs" :key="blog.id">
      <h2></h2>
      <p></p>
    </div>
  </main>
</template>

<style scoped>
header {
  line-height: 1.5;
}
</style>

// apps/admin/src/App.tsx
import { useEffect, useState } from "react";
import { Blog } from "types";
import "./App.css";
import axios from "axios";

function App() {
  const [blogs, setBlogs] = useState<Blog[]>([]);

  useEffect(() => {
    axios
      .get("http://localhost:8000/blogs")
      .then((res) => {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
        setBlogs(res.data.blogs as Blog[]);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);

  return (
    <>
      {blogs.map((blog: Blog) => (
        <div key={blog.id}>
          <h1>{blog.title}</h1>
          <p>{blog.content}</p>
        </div>
      ))}
    </>
  );
}

export default App;
